# -*- coding: utf-8 -*-
lines = []
lines.append(r'\newpage')
lines.append('')
lines.append(r'\subsection{Applying TOPSIS-RAD with fixed DPL (Toy Example C)}')
lines.append(r'\label{subsec:example_C}')
lines.append('')
lines.append(r'In Toy Example C we apply TOPSIS-RAD to the same dataset and $VPL$ used in Toy Example B, but now with a \emph{fixed}, decision-maker-defined $DPL$ instead of the data-driven column maxima. The purpose is to show that anchoring the normalisation frontiers to explicit saturation thresholds makes the ranking invariant to changes in the composition of the dataset, thereby removing the instability illustrated in Toy Example B.')
lines.append('')
lines.append(r'\begin{itemize}')
lines.append('')
lines.append(r'\item [Step 1:] \textbf{Get the inputs of the Decision Problem.}')
lines.append('')
lines.append(r'\begin{enumerate}')
lines.append(r'    \item [Step 1.a:] Get the initial data. The same performance matrix $G$ and equal weights $w_j = 0.25$ from Toy Example A are used here; they appear in \autoref{fig:fig_app_toy_example_1_G_matrix}.')
lines.append('')
lines.append(r'    \item [Step 1.b:] Get \textit{Desired Performance Levels} ($DPL$) and \textit{Vetoed Performance Levels} ($VPL$) from the Decision Maker.')
lines.append('')
lines.append(r'    The $VPL$ is unchanged from Toy Example B:')
lines.append(r'    \[')
lines.append(r'        VPL = \{42,\; 40,\; 30,\; 65\},')
lines.append(r'    \]')
lines.append(r'    so $A_8$ is still excluded because $g_{8,C_3} = 18 < VPL_{C_3} = 30$. The $DPL$ is now set by the decision maker as fixed saturation thresholds, independent of the dataset:')
lines.append(r'    \[')
lines.append(r'        DPL = \{98,\; 90,\; 85,\; 80\}.')
lines.append(r'    \]')
lines.append(r'    Crucially, $DPL_{C_3} = 85$ is \emph{below} the $C_3$ value of $A_4$ ($g_{4,C_3} = 88$), and $DPL_{C_4} = 80$ is \emph{below} the $C_4$ values of $A_4$ ($g_{4,C_4} = 84$), $A_5$ ($g_{5,C_4} = 100$), and $A_{10}$ ($g_{10,C_4} = 81$). These alternatives will be clipped in the next step. The settings are shown in \autoref{fig:fig_toy_example_3_VPL_and_DPL}.')
lines.append('')
lines.append(r'\end{enumerate}')
lines.append('')
lines.append(r'\begin{figure}[H]')
lines.append(r'    \centering')
lines.append(r'    \includegraphics[width=0.65\linewidth]{fig_toy_example_3_VPL_and_DPL.png}')
lines.append(r'    \caption{TOPSIS-RAD settings for Toy Example C: fixed DM-defined $DPL$ per criterion (notably $DPL_{C_4}=80$).}')
lines.append(r'    \label{fig:fig_toy_example_3_VPL_and_DPL}')
lines.append(r'\end{figure}')
lines.append('')
lines.append(r'\item [Step 2:] \textbf{Obtain the normalised weights $W$.} The same equal weights are used; they appear in \autoref{fig:fig_app_toy_example_1_weights}.')
lines.append('')
lines.append(r'\item [Step 3:] \textbf{Obtain the qualified and desired-constrained decision matrix.}')
lines.append('')
lines.append(r'  \begin{enumerate}[label=Step 3.\alph*:]')
lines.append('')
lines.append(r'    \item \textbf{Determine the \emph{qualified} alternatives ($A^{q}$).} The $VPL$ is identical to Toy Example B, so the qualified set is the same:')
lines.append(r'    $$A^{q} = \{A_1,\; A_2,\; A_3,\; A_4,\; A_5,\; A_6,\; A_7,\; A_9,\; A_{10}\}.$$')
lines.append('')
lines.append(r'    \item \textbf{Obtain the Qualified Decision Matrix ($G^q$)} by retaining the rows of $a_k \in A^q$ (the same $9 \times 4$ submatrix as in Toy Example B).')
lines.append('')
lines.append(r'    \item \textbf{Clip performances above $DPL$ to obtain $G^d$.} With $DPL_{C_3} = 85$, one alternative exceeds the threshold in $C_3$ and is capped: $g^d_{4,C_3} = \min(88, 85) = 85$. With $DPL_{C_4} = 80$, three alternatives exceed the threshold in $C_4$ and are capped: $g^d_{4,C_4} = \min(84, 80) = 80$, $g^d_{5,C_4} = \min(100, 80) = 80$, and $g^d_{10,C_4} = \min(81, 80) = 80$.')
lines.append(r'    All other values lie at or below their respective $DPL$ entries and are unchanged. The resulting matrix $G^d$ is shown in \autoref{fig:fig_app_toy_example_3_Gd}.')
lines.append('')
lines.append(r'  \end{enumerate}')
lines.append('')
lines.append(r'\begin{figure}[H]')
lines.append(r'    \centering')
lines.append(r'    \includegraphics[width=0.40\linewidth]{fig_app_toy_example_3_Gq.png}')
lines.append(r'    \caption{DPL-clipped qualified matrix $G^d$ for Toy Example C: $A_4$ and $A_5$ are capped at $DPL_{C_3}=85$ in $C_3$; $A_4$, $A_5$, and $A_{10}$ are capped at $DPL_{C_4}=80$ in $C_4$.}')
lines.append(r'    \label{fig:fig_app_toy_example_3_Gd}')
lines.append(r'\end{figure}')
lines.append('')
lines.append(r'\item [Step 4:] \textbf{Compute the normalised matrix $R_{k\times n}$ and the weighted normalised matrix $T_{k\times n}$.}')
lines.append(r'Applying the min-max normalisation of \autoref{eq:rad_normalization} to $G^d$ and multiplying by $w_j = 0.25$ yields the matrices $R$ and $T$ shown in \autoref{fig:fig_app_toy_example_3_Norm_Weighted}. The key changes relative to Toy Example B are in criteria $C_3$ and $C_4$. In $C_3$, clipping $A_4$ from 88 to 85 brings the column range to $[62, 85]$ instead of $[62, 88]$; both $A_4$ and $A_5$ now achieve the maximum normalised score of 1.0000 on $C_3$. In $C_4$, clipping $A_4$ (84$\to$80), $A_5$ (100$\to$80), and $A_{10}$ (81$\to$80) brings the column range to $[65, 80]$ instead of $[65, 100]$; $A_2$, $A_4$, $A_5$, and $A_{10}$ all achieve the maximum normalised score of 1.0000 on $C_4$, while $A_7$ (with $g_{7,C_4} = 65$) still receives 0.0000.')
lines.append('')
lines.append(r'\begin{figure}[H]')
lines.append(r'    \centering')
lines.append(r'    \begin{subfigure}{0.52\textwidth}')
lines.append(r'        \centering')
lines.append(r'        \includegraphics[width=\linewidth]{fig_app_toy_example_3_Normalized.png}')
lines.append(r'        \caption{Normalised matrix $R$ (Toy Example C)}')
lines.append(r'        \label{fig:fig_app_toy_example_3_Normalized}')
lines.append(r'    \end{subfigure}')
lines.append(r'    \hfill')
lines.append(r'    \begin{subfigure}{0.43\textwidth}')
lines.append(r'        \centering')
lines.append(r'        \includegraphics[width=\linewidth]{fig_app_toy_example_3_Weighted.png}')
lines.append(r'        \caption{Weighted matrix $T$ (Toy Example C)}')
lines.append(r'        \label{fig:fig_app_toy_example_3_Weighted}')
lines.append(r'    \end{subfigure}')
lines.append(r'    \caption{Normalised and weighted matrices for Toy Example C.}')
lines.append(r'    \label{fig:fig_app_toy_example_3_Norm_Weighted}')
lines.append(r'\end{figure}')
lines.append('')
lines.append(r'\item [Step 5:] \textbf{Identify the Desired Normalised Level ($DNL$) and Vetoed Normalised Level ($VNL$) arrays.} Because every criterion still has at least one alternative at each normalised extreme, the reference arrays are identical to Toy Example B, as shown in \autoref{fig:fig_app_toy_example_3_DNL_VNL}:')
lines.append(r'\[')
lines.append(r'    DNL = \{0.25,\; 0.25,\; 0.25,\; 0.25\}, \qquad VNL = \{0,\; 0,\; 0,\; 0\}.')
lines.append(r'\]')
lines.append('')
lines.append(r'\begin{figure}[H]')
lines.append(r'    \centering')
lines.append(r'    \includegraphics[width=0.45\linewidth]{fig_app_toy_example_3_DNL_VNL.png}')
lines.append(r'    \caption{Toy Example C: $DNL$ and $VNL$ reference arrays (identical to Toy Example B).}')
lines.append(r'    \label{fig:fig_app_toy_example_3_DNL_VNL}')
lines.append(r'\end{figure}')
lines.append('')
lines.append(r'\item [Step 6:] \textbf{Compute the distances of each qualified alternative $a_k \in A^q$ to the $DNL$ and $VNL$ arrays.} The Euclidean distances are given in \autoref{fig:fig_app_toy_example_3_Distances}. Alternative $A_7$ remains equidistant: $d_{ib}(A_7) = d_{iw}(A_7) = 0.3536$, because its weighted scores are $t_{7,C_1} = t_{7,C_2} = 0.25$ (equal to $DNL$) and $t_{7,C_3} = t_{7,C_4} = 0$ (equal to $VNL$), yielding a score of exactly $S_{7w} = 0.5000$.')
lines.append('')
lines.append(r'\begin{figure}[H]')
lines.append(r'    \centering')
lines.append(r'    \includegraphics[width=0.45\linewidth]{fig_app_toy_example_3_Distances.png}')
lines.append(r'    \caption{Toy Example C: distances $d_{ib}$ (to $DNL$) and $d_{iw}$ (to $VNL$) for each qualified alternative.}')
lines.append(r'    \label{fig:fig_app_toy_example_3_Distances}')
lines.append(r'\end{figure}')
lines.append('')
lines.append(r'\item [Step 7:] \textbf{Compute the relative closeness score ($S_{iw}$) and rank the alternatives.} The resulting scores and final ranking are shown in \autoref{fig:fig_app_toy_example_3_ScoresChart}.')
lines.append('')
lines.append(r'\begin{figure}[H]')
lines.append(r'    \centering')
lines.append(r'    \begin{subfigure}{0.43\textwidth}')
lines.append(r'        \centering')
lines.append(r'        \includegraphics[width=\linewidth]{fig_app_toy_example_3_Scores.png}')
lines.append(r'        \caption{$S_{iw}$ scores (Toy Example C)}')
lines.append(r'        \label{fig:fig_app_toy_example_3_Scores}')
lines.append(r'    \end{subfigure}')
lines.append(r'    \hfill')
lines.append(r'    \begin{subfigure}{0.52\textwidth}')
lines.append(r'        \centering')
lines.append(r'        \includegraphics[width=\linewidth]{_fig_toy_topsis_rad_C.png}')
lines.append(r'        \caption{Final ranking by $S_{iw}$ score (Toy Example C)}')
lines.append(r'        \label{fig:fig_toy_topsis_rad_C}')
lines.append(r'    \end{subfigure}')
lines.append(r'    \caption{Scores and final ranking for Toy Example C: $A_7$ falls to 7\textsuperscript{th} place.}')
lines.append(r'    \label{fig:fig_app_toy_example_3_ScoresChart}')
lines.append(r'\end{figure}')
lines.append('')
lines.append(r'\end{itemize}')
lines.append('')
lines.append(r'\autoref{tab:toy_example_A_B_C} places the three rankings side by side.')
lines.append('')
lines.append(r'\begin{table}[htbp]')
lines.append(r'    \centering')
lines.append(r'    \caption{Comparing rankings: traditional TOPSIS (Toy Example A), TOPSIS-RAD with data-driven $DPL$ (Toy Example B), and TOPSIS-RAD with fixed $DPL$ (Toy Example C).}')
lines.append(r'    \small')
lines.append(r'    \begin{tabular}{p{2.4cm}|p{0.38cm}p{0.38cm}p{0.38cm}p{0.38cm}p{0.38cm}p{0.38cm}p{0.38cm}p{0.38cm}p{0.38cm}p{0.38cm}}')
lines.append(r'    \hline')
lines.append(r'    & \multicolumn{10}{c}{Ranking position} \\')
lines.append(r'    \cline{2-11}')
lines.append(r'    Toy Example & $1^{st}$ & $2^{nd}$ & $3^{rd}$ & $4^{th}$ & $5^{th}$ & $6^{th}$ & $7^{th}$ & $8^{th}$ & $9^{th}$ & $10^{th}$ \\')
lines.append(r'    \hline')
lines.append(r'    A (TOPSIS)         & A7 & A5 & A4 & A9 & A2 & A1 & A6 & A10 & A3 & A8 \\')
lines.append(r'    B (RAD, data DPL)  & A5 & A4 & A7 & A9 & A2 & A10 & A1 & A3 & A6 & --- \\')
lines.append(r'    C (RAD, fixed DPL) & A4 & A5 & A2 & A9 & A10 & A1 & A7 & A3 & A6 & --- \\')
lines.append(r'    \hline')
lines.append(r'    \end{tabular}')
lines.append(r'    \label{tab:toy_example_A_B_C}')
lines.append(r'\end{table}')
lines.append('')
lines.append('')
lines.append(r'\autoref{tab:toy_example_A_B_C} shows that the rank reversal for $A_7$ persists in Toy Example C: it falls from 1\textsuperscript{st} place (Toy A) to 7\textsuperscript{th} (Toy C). Comparing Toy B and Toy C, the most notable shift is that $A_4$ rises from 2\textsuperscript{nd} to 1\textsuperscript{st}: in Toy B, $A_4$ led on $C_3$ (column maximum $g_{4,C_3}=88$) but trailed $A_5$ on $C_4$; in Toy C, the fixed $DPL_{C_3}=85$ caps $A_4$\'s $C_3$ advantage, tying it with $A_5$ at the $C_3$ maximum, and $DPL_{C_4}=80$ simultaneously eliminates $A_5$\'s dominant $C_4$ value (100$\\to$80). With $C_3$ and $C_4$ performances equalised between $A_4$ and $A_5$, the tie is broken by $C_2$, where $A_4$ ($g_{4,C_2}=72$) outperforms $A_5$ ($g_{5,C_2}=68$). Alternative $A_9$ remains 4\textsuperscript{th} in both Toy B and Toy C.')
lines.append('')
lines.append(r'The driving mechanism is the combined $C_3$ and $C_4$ clipping introduced by the fixed $DPL$. In Toy Example B, the data-driven upper frontier for $C_4$ was $\max_{k}(g^d_{k,C_4}) = 100$ (set by $A_5$), so $A_5$ alone achieved the maximum normalised score on $C_4$. In Toy Example C, capping at 80 places $A_2$, $A_4$, $A_5$, and $A_{10}$ at the same maximum $C_4$ score of 1.0000. Similarly, capping $C_3$ at 85 removes $A_4$\'s outlier advantage, tying it with $A_5$ at the $C_3$ maximum. Alternative $A_1$ (with $g_{1,C_4} = 78$) now achieves a normalised $C_4$ score of $(78-65)/(80-65) = 0.8667$ compared to $(78-65)/(100-65) = 0.3714$ in Toy B, which is sufficient for it to overtake $A_7$ ($S_{1w} = 0.5022 > S_{7w} = 0.5000$).')
lines.append('')
lines.append(r'The critical advantage of fixed $DPL$ frontiers is \emph{invariance to dataset composition}. In Toy Example B, the $C_4$ normalisation range was $[65, 100]$ \emph{only because $A_5$ happened to be present with an extreme value of 100}; adding or removing any alternative with a different $C_4$ value would shift the upper bound and change all other normalised scores. In Toy Example C, the upper frontier is anchored at $DPL_{C_4} = 80$ regardless of which alternatives are evaluated. Any alternative with $C_4 > 80$ is simply capped; any alternative with $C_4 \leq 80$ is normalised against the same fixed span $[65, 80]$. The ranking therefore remains stable under changes in the composition of the evaluated set---precisely the property that data-driven normalisation cannot guarantee, as illustrated by the instability demonstrated between Toy Examples A and B.')

out_path = r'C:\Users\HELDE\Dropbox\latex_nova\Topis_RAD_Working - Sem Telas\__sec___f__63_results_toy_C_dpl.tex'
with open(out_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print(f'Written {len(lines)} lines to {out_path}')
